# Generated by Django 4.1.1 on 2022-09-26 21:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Filmwork',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                (
                    'description',
                    models.TextField(blank=True, null=True, verbose_name='description'),
                ),
                (
                    'creation_date',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='creation_date'
                    ),
                ),
                (
                    'certificate',
                    models.CharField(
                        blank=True, max_length=512, verbose_name='certificate'
                    ),
                ),
                (
                    'file_path',
                    models.FileField(
                        blank=True, null=True, upload_to='movies/', verbose_name='file'
                    ),
                ),
                (
                    'rating',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='rating',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('movie', 'Movie'), ('tv_show', 'Tv Show')],
                        default='movie',
                        max_length=7,
                        verbose_name='Тип',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Film_work',
                'verbose_name_plural': 'Film_works',
                'db_table': 'content"."film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                (
                    'description',
                    models.TextField(blank=True, null=True, verbose_name='description'),
                ),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'content"."genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'full_name',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='full_name'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='PersonFilmwork',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('role', models.TextField(null=True, verbose_name='role')),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'film_work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='movies.filmwork',
                    ),
                ),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='movies.person'
                    ),
                ),
            ],
            options={
                'db_table': 'content"."person_film_work',
            },
        ),
        migrations.CreateModel(
            name='GenreFilmwork',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'film_work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='movies.filmwork',
                    ),
                ),
                (
                    'genre',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='movies.genre'
                    ),
                ),
            ],
            options={
                'db_table': 'content"."genre_film_work',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(
                through='movies.GenreFilmwork', to='movies.genre'
            ),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='preson',
            field=models.ManyToManyField(
                through='movies.PersonFilmwork', to='movies.person'
            ),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(
                fields=['person_id', 'film_work_id'],
                name='person_film_person__632e95_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(
                fields=('genre_id', 'film_work_id'), name='unique_genre'
            ),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(
                fields=['creation_date'], name='film_work_creatio_02a6ad_idx'
            ),
        ),
    ]
