# Generated by Django 4.1.1 on 2022-09-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_filmwork_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='certificate',
            field=models.CharField(
                blank=True, max_length=512, verbose_name='certificate'
            ),
        ),
    ]
