# Generated by Django 4.1.1 on 2022-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_filmwork_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(
                choices=[('movie', 'Movie'), ('tv_show', 'Tv Show')],
                default='movie',
                max_length=7,
                verbose_name='Тип',
            ),
        ),
    ]
