# Generated by Django 4.1.1 on 2022-09-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_filmwork_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(
                choices=[('mo', 'movie'), ('tv', 'tv_show')],
                default='mo',
                max_length=2,
                verbose_name='Тип',
            ),
        ),
    ]
